Fail properly on no connection.

diff --git a/ccr-tools b/ccr-tools
--- a/ccr-tools
+++ b/ccr-tools
@@ -161,20 +161,26 @@ login() {
 
     # logs in to ccr and keeps session alive
     umask 077
-    if [[ ! -e "$tempdir/cjar" || $rememberme != 1 || $(expired) == 1 ]]; then
-      [[ $(expired) == 1 ]] && echo "Your session has expired."
-      while [[ -z $user ]]; do read -p "please enter your CCR username: " user; done
-      while [[ -z $pass ]]; do read -p "please enter your CCR password: " -s pass && echo; done
-      [[ $rememberme == 1 ]] && args=('-d' 'remember_me=on')
-      curl -Ss --cookie-jar "$tempdir/cjar" --output /dev/null ${ccrbaseurl} 
-      curl -Ss --cookie "$tempdir/cjar" --cookie-jar "$tempdir/cjar"  \
+    failure=0
+    curl -Ss --cookie-jar "$tempdir/cjar" --output /dev/null ${ccrbaseurl} || failure=1
+    if [[ $failure = 0 && ( ! -e "$tempdir/cjar" || $rememberme != 1 || $(expired) == 1 ) ]]; then
+        [[ $(expired) == 1 ]] && echo "Your session has expired."
+        while [[ -z $user ]]; do read -p "please enter your CCR username: " user; done
+        while [[ -z $pass ]]; do read -p "please enter your CCR password: " -s pass && echo; done
+        [[ $rememberme == 1 ]] && args=('-d' 'remember_me=on')
+        curl -Ss --cookie "$tempdir/cjar" --cookie-jar "$tempdir/cjar"  \
                --data "user=$user" --data "passwd=$(urlencode $pass)" \
                --location --output "$tempdir/ccrvote.login"  \
-               ${args[@]} ${ccrbaseurl}
+               ${args[@]} ${ccrbaseurl} || failure=1
+        
+        if grep --quiet "'error'>Bad username or password" "$tempdir/ccrvote.login";then
+            echo "incorrect password: check $configrc file"
+            die 1
+        fi
     fi
-
-    if grep --quiet "'error'>Bad username or password" "$tempdir/ccrvote.login";then
-        echo "incorrect password: check $configrc file"
+    
+    if [[ ! $failure = 0 ]]; then
+        echo "Failure (no connection?)"
         die 1
     fi
 }
